# =============================================================================
# RUBOCOP CONFIGURATION
# =============================================================================
#
# RuboCop is a Ruby code style checker and formatter. It enforces:
# 1. Consistent code style (indentation, naming, etc.)
# 2. Best practices (avoiding error-prone patterns)
# 3. Rails-specific conventions
#
# WHY USE A LINTER?
# - Consistent codebase is easier to read and maintain
# - Catches bugs before they reach production
# - Reduces code review nitpicking about style
# - Onboards new developers faster (code looks familiar)
#
# HOW TO USE:
# - Run: bundle exec rubocop
# - Auto-fix: bundle exec rubocop -a (safe fixes)
# - Auto-fix all: bundle exec rubocop -A (including unsafe)
#
# =============================================================================

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  # Target Ruby version
  TargetRubyVersion: 3.2

  # New cops are pending by default; enable them explicitly
  NewCops: enable

  # Exclude generated files and vendor code
  Exclude:
    - 'db/schema.rb'           # Auto-generated by Rails
    - 'db/migrate/**/*'        # Migrations are often messy, that's OK
    - 'bin/**/*'               # Rails scripts
    - 'vendor/**/*'            # Third-party code
    - 'node_modules/**/*'      # Frontend dependencies
    - 'tmp/**/*'               # Temporary files
    - 'config/initializers/devise.rb'  # Devise generates this

# =============================================================================
# STYLE COPS
# =============================================================================

# Prefer double quotes for consistency with other languages
# Ruby allows both, but double quotes enable interpolation
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Allow both `-> {}` and `lambda {}` syntax
Style/Lambda:
  EnforcedStyle: literal

# Don't require documentation for every class
# In a small project, good naming is often sufficient
Style/Documentation:
  Enabled: false

# Allow `and`/`or` for control flow (common Rails pattern)
Style/AndOr:
  EnforcedStyle: conditionals

# Frozen string literal comment is important for performance
# Ruby can intern frozen strings, saving memory
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# =============================================================================
# LAYOUT COPS
# =============================================================================

# 100 characters per line is reasonable for modern screens
Layout/LineLength:
  Max: 100
  AllowedPatterns:
    - '^\s*#'  # Allow long comments (URLs, etc.)

# Consistent hash formatting
Layout/HashAlignment:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

# =============================================================================
# METRICS COPS
# =============================================================================

# Method length - 15 is strict but encourages small methods
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/seeds.rb'  # Seeds can be long

# Class length - larger classes are sometimes necessary
Metrics/ClassLength:
  Max: 200

# Block length - RSpec blocks can be long
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'
    - 'db/seeds.rb'

# ABC metric (Assignment, Branch, Condition complexity)
Metrics/AbcSize:
  Max: 25

# =============================================================================
# RAILS COPS
# =============================================================================

# Use Time.current instead of Time.now (respects Rails timezone)
Rails/TimeZone:
  Enabled: true

# Prefer pluck for selecting a single column
Rails/Pluck:
  Enabled: true

# Don't skip validation callbacks (dangerous)
Rails/SkipsModelValidations:
  Enabled: true

# =============================================================================
# RSPEC COPS
# =============================================================================

# Allow longer example groups in specs
RSpec/ExampleLength:
  Max: 15

# Allow multiple expectations when testing related things
RSpec/MultipleExpectations:
  Max: 5

# Allow nested groups for better organization
RSpec/NestedGroups:
  Max: 4

# Allow longer descriptions
RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'  # Request specs don't always map to classes

# =============================================================================
# NAMING COPS
# =============================================================================

# Allow common short variable names
Naming/MethodParameterName:
  AllowedNames:
    - id
    - to
    - by

# Allow predicate methods without question marks in some cases
Naming/PredicateName:
  AllowedMethods:
    - has_permission?

# =============================================================================
# PERFORMANCE COPS
# =============================================================================

# Use count instead of size/length on ActiveRecord
Performance/Count:
  Enabled: true

# Use exists? instead of present? when only checking existence
Performance/RedundantMerge:
  Enabled: true
